### ISSUE TITLE
hub move format: parsing might fail if captures aren't ordered

### ISSUE THREAD

**Issue by colette-b** [AttackingOrDefending/pydraughts#23]
Parsing moves in hub format might fail, if the move has the captures unordered.
I use this definition of the hub protocol, which says the captures can be ordered arbitrarily: https://github.com/rhalbersma/scan/blob/master/protocol.txt
In the example below, first move is parsed correctly and the second one raises an error.
```
import draughts

g2 = draughts.Game(variant='brazilian', fen='Bbbbbebbbbbwbeeeewweeweeewwewwwww')
move_ok = draughts.Move(board=g2, hub_move='8x13x11x17x18')
move_bad = draughts.Move(board=g2, hub_move='8x13x11x18x17')
```

**Comment by AttackingOrDefending** [comment]
I also used this definition of the Hub protocol but I can't find the part that it says that captures can be ordered arbitrarily. Hub engines return the captures in order. I have created a PR with a fix for this.

**Comment by colette-b** [comment]
The linked file says: 
_"For captures, all the captured pieces (but not the pivots) are included in **any order** like this: from x to x captured x captured ... without any spaces."_
Anyway, I checked the pull request and it fixes the issue for me. Thank you very much! :+1:

**Comment by AttackingOrDefending** [comment]
Now I saw it. Thanks.
