### ISSUE TITLE
Russian draughts

### ISSUE THREAD

**Issue by ArturasTv** [AttackingOrDefending/pydraughts#28]
The Russian draughts have rule that if you have started to capture a sequence of enemy pieces that you need to finish it, you cannot ignore it and do not finish the multiple capture jump.

For example, this position should have only one valid move, not two
fen="W:Wh6:Bg7,c5,d2"

**Comment by AttackingOrDefending** [comment]
@ArturasTv Thanks for the bug report. This issue should be fixed now. I have released a new version of pydraughts (0.6.1). Install the new one and it should be working fine.
