### ISSUE TITLE
Exploring Game Development with AI: Engine Examples and Tutorials

### ISSUE THREAD

**Issue by Saidalo1** [AttackingOrDefending/pydraughts#41]
It would be great to see examples of game engines we can use, along with tutorials on installation, configuration, and game play. Additionally, it would be exciting to incorporate AI into this project, enabling interaction between players and the engine using this library and UI.

**Comment by AttackingOrDefending** [comment]
Hub engines:
[Kingsrow (international)](https://edgilbert.org/InternationalDraughts/download_links.htm)
[Scan](https://hjetten.home.xs4all.nl/scan/scan.html)
DXP engines:
[Kingsrow (international)](https://edgilbert.org/InternationalDraughts/download_links.htm)
[Scan](https://hjetten.home.xs4all.nl/scan/scan.html)
[Moby Dam](https://hjetten.home.xs4all.nl/mobydam/mobydam.html)
Checkerboard engines:
[Kingsrow (english)](https://edgilbert.org/EnglishCheckers/KingsRowEnglish.htm)
[Kingsrow (italian)](https://edgilbert.org/ItalianCheckers/KingsRowItalian.htm)
[Cake](https://www.fierz.ch/download.php)
[Kallisto](https://www.igorkorshunov.narod.ru/Draughts/Kallisto4.rar)

For more engines see [here](https://docs.google.com/spreadsheet/ccc?key=0Asz2vQounJs3dGoydFVoWUkyMHE4U25QMHRwMUViSnc).

Programs using pydraughts:
https://github.com/d3da/checkers-rl
https://github.com/Palmirka/Evolutionary-checkers

I will create a PR with links to engines one can use, and a section for programs using pydraughts.

**Comment by Saidalo1** [comment]
Great! Thank you very much! But unfortunately I could not use them to build game between bot and people in Russian checkers of my fault. But library is great!

**Comment by Saidalo1** [comment]
Great! Thank you very much! But unfortunately I could not use them to build game between bot and people in Russian checkers of my fault. But library is great!
